### ISSUE TITLE
A way to get the current color temperature?

### ISSUE THREAD

**Issue by Evi1M4chine** [mgudemann/sct#1]
I have a small cron script that simulates gradual dawn and dusk. But I currently only change the brightness.
I want to change the color temperature too.
But to be gradual, I have to know the normal temperature too. Then I would look up the color temperature of when the sun is nearly completely below the horizon, and slowly fade between the two.

So it would be cool if the program had an option (like `--get`) to print the current color temperature as a number.

(Maybe one could even integrate the entire logic for that fading… Currently, I use fade for an hour, and use the start minute, which I pull from my desktop weather widget, plus the current time to do it. This needs fixing though, as I would prefer if it would be more flexible. Also, the weather widget is not really necessary, which is nice, since it is currently broken anyway. ^^)

**Comment by Evi1M4chine** [comment]
I used the version 0.4 of this script, that is included with Gentoo, but doesn’t have the brightness functionality, and added a function to read the current temperature, using the  `--get` parameter.

It’s my very first C coding of any kind, so be gentle. :)

It is only halfway there. It only works at 100% brightness, and still needs to do the reverse of the `s_avg` function to calculate the temperature from those values.
But it’s a start, I hope. :)

Since github doesn’t seem to have a nice way to include patches, here it is, gzip’d:
[0.4-get-temperature.patch.gz](https://github.com/mgudemann/sct/files/1515914/0.4-get-temperature.patch.gz)

**Comment by Evi1M4chine** [comment]
Btw, a better way than sct would probably, to integrate the functionality directly into `xrandr` as a `--temperature` parameter. That way it would work with both custom brightness and custom gamma.

**Comment by mgudemann** [comment]
@Evi1M4chine Hi, please use the [pull request](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project) feature of github for this. It greatly facilitates providing patches and discussions about code. 

Briefly, you would fork the repo, create a branch for your change and provide a PR for that branch here. Then we can discuss the changes by annotating the code and finally I can merge the branch here.

**Comment by mgudemann** [comment]
inactive for > 2y
