### ISSUE TITLE
Compiling fails on Devuan 12 (Daedalus) / Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by ghost** [mgudemann/sct#5]
Hi. I decided to go back to your sct, cause it is way smaller than xsct. 
I used it under Debian 11, but now on Devuan 12 I can not compile it anymore:

```
gcc -I/usr/local/include -L/usr/local/lib sct.c -o sct -lXrandr -lX11
In file included from sct.c:2:
/usr/include/X11/Xlib.h:38:10: fatal error: sys/types.h: File or directory not found
   38 | #include <sys/types.h>
      |          ^~~~~~~~~~~~~
```

**Comment by mgudemann** [comment]
Thanks for the report. Do you have a `sys/types.h` somewhere? This might just be
missing from the include path.

i.e. what does `find /usr -iname "types.h"` say?

**Comment by ghost** [comment]
> i.e. what does `find /usr -iname "types.h"` say? 

Gives nothing as output.

**Comment by mgudemann** [comment]
Does it work when you install the `libc6-dev` package?

I do not have a Devuan installation, but searched with

https://pkginfo.devuan.org/cgi-bin/policy-query.html?c=file&q=sys%2Ftypes.h&x=submit

**Comment by ghost** [comment]
Yes that was missing, also libxrandr-dev
Thank you very much. :)
